import { db } from './index'
import { articles } from './schema'

const seedArticles = [
  {
    content: 'The only way to do great work is to love what you do.',
    translation: '做出伟大成就的唯一途径是热爱你所做的事。',
    difficulty: '1.0',
    dLen: '0',
    dVocab: '0',
    dSyntax: '0',
    wordCount: 13,
    sourceType: 'quote',
    author: 'Steve Jobs',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Stay hungry, stay foolish.',
    translation: '求知若饥，虚心若愚。',
    difficulty: '1.0',
    dLen: '0',
    dVocab: '0',
    dSyntax: '0',
    wordCount: 4,
    sourceType: 'quote',
    author: 'Steve Jobs',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Life is what happens when you are busy making other plans.',
    translation: '生活就是在你忙于制定其他计划时所发生的事情。',
    difficulty: '1.2',
    dLen: '0',
    dVocab: '0.15',
    dSyntax: '0',
    wordCount: 12,
    sourceType: 'quote',
    author: 'John Lennon',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'In the middle of difficulty lies opportunity.',
    translation: '在困难之中蕴藏着机会。',
    difficulty: '1.3',
    dLen: '0',
    dVocab: '0.3',
    dSyntax: '0',
    wordCount: 8,
    sourceType: 'quote',
    author: 'Albert Einstein',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'The best way to predict the future is to create it.',
    translation: '预测未来最好的方式就是创造它。',
    difficulty: '1.4',
    dLen: '0',
    dVocab: '0.15',
    dSyntax: '0.2',
    wordCount: 11,
    sourceType: 'quote',
    author: 'Peter Drucker',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'It does not matter how slowly you go as long as you do not stop.',
    translation: '只要你不停下，走得慢一点也没关系。',
    difficulty: '1.5',
    dLen: '0',
    dVocab: '0.15',
    dSyntax: '0.3',
    wordCount: 16,
    sourceType: 'quote',
    author: 'Confucius',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
    translation: '成功不是终点，失败也非末日：最重要的是继续前进的勇气。',
    difficulty: '1.8',
    dLen: '0.25',
    dVocab: '0.3',
    dSyntax: '0.2',
    wordCount: 18,
    sourceType: 'quote',
    author: 'Winston Churchill',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'The only person you are destined to become is the person you decide to be.',
    translation: '你注定成为的唯一人，是你决定成为的那个人。',
    difficulty: '1.8',
    dLen: '0.1',
    dVocab: '0.45',
    dSyntax: '0.2',
    wordCount: 15,
    sourceType: 'quote',
    author: 'Ralph Waldo Emerson',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'We cannot solve our problems with the same thinking we used when we created them.',
    translation: '我们无法用创造问题时的思维方式来解决问题。',
    difficulty: '1.9',
    dLen: '0.1',
    dVocab: '0.45',
    dSyntax: '0.3',
    wordCount: 16,
    sourceType: 'quote',
    author: 'Albert Einstein',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    translation: '与我们内心的力量相比，身后和眼前的事物都微不足道。',
    difficulty: '2.0',
    dLen: '0.2',
    dVocab: '0.3',
    dSyntax: '0.5',
    wordCount: 19,
    sourceType: 'quote',
    author: 'Ralph Waldo Emerson',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'The future belongs to those who believe in the beauty of their dreams.',
    translation: '未来属于那些相信梦想之美的人。',
    difficulty: '2.0',
    dLen: '0.1',
    dVocab: '0.6',
    dSyntax: '0.3',
    wordCount: 14,
    sourceType: 'quote',
    author: 'Eleanor Roosevelt',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Do not wait for leaders; do it alone, person to person. Be faithful in small things because it is in them that your strength lies.',
    translation: '不要等待领袖；一个人一个人地去做。在小事上忠心，因为你的力量就在其中。',
    difficulty: '2.3',
    dLen: '0.3',
    dVocab: '0.45',
    dSyntax: '0.5',
    wordCount: 27,
    sourceType: 'quote',
    author: 'Mother Teresa',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.',
    translation: '当一扇幸福之门关闭时，另一扇会打开；但我们常常凝视着关闭的门太久，以至于看不到已为我们打开的那扇门。',
    difficulty: '2.5',
    dLen: '0.5',
    dVocab: '0.45',
    dSyntax: '0.5',
    wordCount: 33,
    sourceType: 'quote',
    author: 'Helen Keller',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    translation: '生命中最伟大的光辉不在于永不坠落，而在于每次坠落后都能重新站起来。',
    difficulty: '2.5',
    dLen: '0.3',
    dVocab: '0.6',
    dSyntax: '0.5',
    wordCount: 20,
    sourceType: 'quote',
    author: 'Nelson Mandela',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.',
    translation: '黑暗无法驱散黑暗，只有光明可以做到；仇恨无法驱散仇恨，只有爱可以做到。',
    difficulty: '2.7',
    dLen: '0.3',
    dVocab: '0.6',
    dSyntax: '0.8',
    wordCount: 23,
    sourceType: 'quote',
    author: 'Martin Luther King Jr.',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Your time is limited, so do not waste it living someone else\'s life. Do not be trapped by dogma — which is living with the results of other people\'s thinking.',
    translation: '你的时间有限，所以不要浪费它去过别人的生活。不要被教条所困——那是活在别人思考的结果里。',
    difficulty: '3.0',
    dLen: '0.5',
    dVocab: '0.75',
    dSyntax: '0.7',
    wordCount: 30,
    sourceType: 'quote',
    author: 'Steve Jobs',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'Twenty years from now you will be more disappointed by the things that you did not do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails.',
    translation: '二十年后，你会更为那些没做过的事后悔，而不是做过的事。所以解开缆绳，驶离安全的港湾，让信风鼓起你的帆。',
    difficulty: '3.5',
    dLen: '1.0',
    dVocab: '0.75',
    dSyntax: '0.7',
    wordCount: 42,
    sourceType: 'quote',
    author: 'Mark Twain',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'I have learned over the years that when one\'s mind is made up, this diminishes fear; knowing what must be done does away with fear.',
    translation: '多年来我学到，当一个人下定决心时，恐惧就会减少；知道必须做什么可以消除恐惧。',
    difficulty: '3.5',
    dLen: '0.5',
    dVocab: '0.9',
    dSyntax: '1.0',
    wordCount: 28,
    sourceType: 'quote',
    author: 'Rosa Parks',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'The world is a fine place and worth fighting for and I hate very much to leave it. And you had a lot of luck, they told me, to have survived the war and to have seen so much.',
    translation: '这世界是个美好的地方，值得为之奋斗，我非常不愿离开它。他们告诉我，你很幸运，能在战争中幸存，看到了这么多。',
    difficulty: '4.0',
    dLen: '1.0',
    dVocab: '1.0',
    dSyntax: '1.0',
    wordCount: 41,
    sourceType: 'quote',
    author: 'Ernest Hemingway',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
  {
    content: 'It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood.',
    translation: '真正重要的不是批评者，不是指出强者如何跌倒、或实干者哪里可以做得更好的人。荣誉属于真正站在竞技场上的人，他的脸上沾满尘土、汗水和鲜血。',
    difficulty: '4.5',
    dLen: '1.5',
    dVocab: '1.0',
    dSyntax: '1.0',
    wordCount: 60,
    sourceType: 'quote',
    author: 'Theodore Roosevelt',
    publishDate: new Date().toISOString().split('T')[0],
    isActive: true,
  },
]

async function main() {
  console.log('Seeding articles...')
  
  for (const article of seedArticles) {
    await db.insert(articles).values(article).onConflictDoNothing()
  }
  
  console.log(`Seeded ${seedArticles.length} articles.`)
  process.exit(0)
}

main().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})